### PR TITLE
Fix search input not filling entire select component, not centered

### PR DESCRIPTION
**Pull request by hmnd**
Setting the width and height of the input to 100% seems to do the trick :)

### CODE REVIEW

**Comment by rob-balfre** [comment]
@hmnd got a REPL of what this is solving?  Not sure I'm following the problem.  Also the PR breaks `multiple` mode.  Thanks

**Comment by hmnd** [comment]
@rob-balfre sorry, I've fixed the issue with `multiple`. I've made [this REPL](https://svelte.dev/repl/c1ef2c0361a2412aae634a8dbc17a616?version=3.50.1) that should demonstrate the issue. Note how the placeholder in the original version is cut off, and if you type a long search keyword, it'll get cut off at the same spot.

This issue doesn't affect `multiple` mode because the input gets `position: relative`, but otherwise the input has `position: absolute` which causes it to shrink and lose vertical centering.

**Comment by rob-balfre** [comment]
I'm not seeing any issues with the original. Are you seeing something different?

Screen Shot 2022-09-17 at 2 26 42 pm

**Comment by hmnd** [comment]
@rob-balfre Huh, interesting... seems that Chromium's default behavior is 100% width, whereas Firefox limits the width

This is what I'm seeing on Firefox:
image

**Comment by rob-balfre** [comment]
@hmnd yeah nice find, I wonder if that's how CSS *should* work or a Firefox bug!

**Pull request merged**
