### PR TITLE
Added a parameter to display a list of options outside the parent element 

### PR DESCRIPTION
**Pull request by thismrojek**
With reference to the notifications:
- https://github.com/rob-balfre/svelte-select/issues/223
- https://github.com/rob-balfre/svelte-select/issues/191
- https://github.com/rob-balfre/svelte-select/issues/229

I have added a parameter (**listOutsideParentContainer**) to display a list of options outside the parent element.

### CODE REVIEW

**Comment by thismrojek** [comment]
@rob-balfre Any chance of a merge in the near future?

**Comment by thismrojek** [comment]
Thank you, @rob-balfre 😄 
I am looking forward for future updates.

**Comment by rob-balfre** [comment]
v5 now displays outside by default.

Thanks for the PR though and very sorry for slow reply.

**Comment by frederikhors** [comment]
@rob-balfre is it possible to add it on v4 too? This is a HUGE problem with v4.

**Pull request closed without merging**
