### PR TITLE
Add events for when you remove or select an item

### PR DESCRIPTION
**Pull request by ssetrom**
This PR adds two convenient events: 

1. "itemRemoved": An event for when you remove an item. The detail of this event is the item removed.
2. "itemSelected": An event for when you select an item. The detail of this event is the item selected.

I also added the "itemCreated" event to the documentation.

### CODE REVIEW

**Comment by rob-balfre** [comment]
@ssetrom thanks for the PR.  There is already `on:select` and `on:clear` so not sure these add anything new.

**Comment by ssetrom** [comment]
@rob-balfre Ah, I should probably have written more about how these events are different. So 'itemSelected' is only ever triggered when the user _directly_ changes a value, and it only returns the one value that was selected/added. This is important because the 'select' event is always tiggered when the data changes ( It can happen because of multiple reasons, for instance the _value_ prop changing ).

Upon some investigation, I've found that actually the 'clear' event totally does what I want it to do! Sorry about that. I believe I added that event for an earlier version of svelte select, and it was probably solving some issue that no longer exists :)

**Comment by rob-balfre** [comment]
@ssetrom I think I'd prefer to change the PR to update `on:select` to only fire when an item is selected instead of having another event.

**Comment by rob-balfre** [comment]
Events in v5 can achieve same result.

Thanks for the PR though and very sorry for slow reply.

**Pull request closed without merging**
