### PR TITLE
Update `selectedValue` when `items` changes

### PR DESCRIPTION
**Pull request by stephenlrandall**
The `selectedValue` doesn't update when `items` is updated. When a label of one of the items is updated externally while that item is selected, the updated label appears in the dropdown menu but `selectedValue` itself doesn't update. REPL here: https://svelte.dev/repl/182a7be1517b4e52b3c6dad0f706ddad?version=3.31.0.

This PR just updates `selectedValue` whenever `items` changes.

### CODE REVIEW

**Comment by rob-balfre** [comment]
Causes loads of failed test I'm afraid.

https://github.com/rob-balfre/svelte-select/tree/pullrequests/stephenlrandall/master

**Comment by stephenlrandall** [comment]
> Causes loads of failed tests I'm afraid.
> 
> https://github.com/rob-balfre/svelte-select/tree/pullrequests/stephenlrandall/master

Sorry, didn't check first! Changed the reactivity of the statement and added checks to only do the updates if both `selectedValue` and `items` are objects, since a string being changed destroys any history of what the original value was. Passes all tests now.

**Comment by rob-balfre** [comment]
Thanks @stephenlrandall taking a look now

**Comment by rob-balfre** [comment]
svelte-select@3.14.2

**Comment by frederikhors** [comment]
Upgrading from `svelte-select@3.14.1` to `svelte-select@3.14.2` breaks my whole project using a lot of them. Wow! Now I need to understand what to do. This is the only change?

**Comment by stephenlrandall** [comment]
> Upgrading from `svelte-select@3.14.1` to `svelte-select@3.14.2` breaks my whole project using a lot of them. Wow! Now I need to understand what to do. This is the only change?

What's breaking exactly? Can you show a REPL of a set-up that the new change breaks?

**Comment by frederikhors** [comment]
It's is not easy. Now I can tell you it's not working `getOptionLabel` and `getSelectionLabel` on the first render. If I choose from list they work.

**Comment by frederikhors** [comment]
Using this:

```js
  const getOptionLabel = (option) => {
    return option.username
  }
```

I get `undefined`.

**Comment by frederikhors** [comment]
I'm using `bind:selectedValue` and it comes from parent.

**Comment by stephenlrandall** [comment]
> Using this:
> 
> ```js
>   const getOptionLabel = (option) => {
>     return option.username
>   }
> ```
> 
> I get `undefined` now instead of the string.

https://svelte.dev/repl/182a7be1517b4e52b3c6dad0f706ddad?version=3.31.0 How close is this to your use case?

**Comment by frederikhors** [comment]
I'm writing it here: https://svelte.dev/repl/800b7f24191848ef8c7984c1ff9edf1e?version=3.31.0 but something is missing. Gimme 5 minutes.

**Comment by frederikhors** [comment]
I think I found the problem. Are you there?

**Comment by frederikhors** [comment]
You can find it here: https://svelte.dev/repl/800b7f24191848ef8c7984c1ff9edf1e?version=3.31.0.

As soon you open the page it loads `John`. After 3 seconds undefined appears!

**Comment by frederikhors** [comment]
With 3.14.1 it doesn't, @rob-balfre.

**Comment by stephenlrandall** [comment]
> With 3.14.1 it doesn't, @rob-balfre.

Screen Shot 2020-12-12 at 4 43 03 PM

Oddly, I don't see this issue. The text in the Select stays the entire time, I never see `undefined`.

**Comment by frederikhors** [comment]
I opened https://github.com/rob-balfre/svelte-select/issues/213.

Wait a moment the REPL is not completed I think.

**Comment by frederikhors** [comment]
@stephenlrandall NOW I GOT IT! https://svelte.dev/repl/800b7f24191848ef8c7984c1ff9edf1e?version=3.31.0

**Pull request merged**
