### PR TITLE
Remove unneeded {#if}

### PR DESCRIPTION
**Pull request by TylerRick**
Just pass disabled={isDisabled}

This removes some duplication.

### CODE REVIEW

**Comment by rob-balfre** [comment]
It's for stupid ie11 support which needs to stay for a bit longer.

**Comment by TylerRick** [comment]
Okay, interesting. Is this documented somewhere (in svelte docs)? Probably not. Oh well...

**Comment by rob-balfre** [comment]
@TylerRick it's an ongoing issue... https://github.com/sveltejs/svelte/issues/4850

IE11 is almost dead, I'll merge this in soon enough. Thanks for the PR!

**Comment by rob-balfre** [comment]
Fixed in v5.

Thanks for the PR.

**Pull request closed without merging**
