### PR TITLE
added var placeholderFontFamily for placeholder styles

### PR DESCRIPTION
**Pull request by gzagura**

### CODE REVIEW

**Comment by rob-balfre** [comment]
@gzagura usually components inherit `font-family` from body or a parent element. If we add this change it will override everyones placeholder font to 'serif' unless they specify `placeholderFontFamily`.

**Comment by gzagura** [comment]
@rob-balfre yeah, didn't think about that, now it's better.

**Comment by rob-balfre** [comment]
I'm happy to approve this but you know you can just achieve something similar with global css or using Svelte's :global(..) ?

https://svelte.dev/repl/f1c601354a524feb883f73e26d71c80c?version=3.12.1

**Comment by gzagura** [comment]
@rob-balfre thank you, didn't know that

**Pull request closed without merging**
